Repository aneoconsulting/ArmoniK, pull requests merged in 2022-09, with the labels that each got.

#484 Add prestop
  armonik-versions.txt
  infrastructure/modules/armonik/compute-plane.tf
  infrastructure/quick-deploy/aws/armonik/parameters.tfvars
  infrastructure/quick-deploy/aws/ecr/parameters.tfvars
  infrastructure/quick-deploy/aws/monitoring/locals.tf
  infrastructure/quick-deploy/aws/monitoring/parameters.tfvars
  infrastructure/quick-deploy/localhost/armonik/parameters.tfvars
  infrastructure/quick-deploy/localhost/monitoring/locals.tf
  infrastructure/quick-deploy/localhost/monitoring/parameters.tfvars
Labels: Enhancement

#501 feat: export results from mongodb using a script
  tools/export-mongo.sh
Labels: Enhancement

#521 Update Admin GUI to 0.6.1
  CHANGELOG.md
  armonik-versions.txt
  infrastructure/quick-deploy/aws/armonik/parameters.tfvars
  infrastructure/quick-deploy/aws/ecr/parameters.tfvars
  infrastructure/quick-deploy/localhost/armonik/parameters.tfvars
Labels: Bug

#528 Update core for ext
  infrastructure/quick-deploy/aws/monitoring/locals.tf
  infrastructure/quick-deploy/localhost/monitoring/locals.tf
Labels: Core, infrastructure
