Repository aneoconsulting/ArmoniK, pull requests merged in 2022-12, with the labels that each got.

#738 Lzk/part
  infrastructure/modules/armonik/locals.tf
  infrastructure/quick-deploy/aws/armonik/parameters.tfvars
  infrastructure/quick-deploy/localhost/armonik/parameters.tfvars
Labels: Enhancement

#733 Update core && add core bench in pipeline
  .github/workflows/deploy.yml
  CHANGELOG.md
  armonik-versions.txt
  infrastructure/quick-deploy/aws/armonik/parameters.tfvars
  infrastructure/quick-deploy/aws/ecr/parameters.tfvars
  infrastructure/quick-deploy/aws/monitoring/locals.tf
  infrastructure/quick-deploy/aws/monitoring/parameters.tfvars
  infrastructure/quick-deploy/localhost/armonik/parameters.tfvars
  infrastructure/quick-deploy/localhost/monitoring/locals.tf
  infrastructure/quick-deploy/localhost/monitoring/parameters.tfvars
Labels: Infrastructure

#583 docs: fix toc of installations
  Documentation/articles/installations/overview.md
  Documentation/articles/installations/toc.md
  Documentation/articles/installations/toc.yml
  Documentation/articles/toc.yml
Labels: Documentation

#751 use env var to show log warnings and higher only for source context Serilog.AspNetCore.RequestLoggingMiddleware
  infrastructure/modules/armonik/log-configmap.tf
Labels: Enhancement

#732 Fix dev env install script to account for the default version change
  infrastructure/utils/scripts/armonik_dev_environment.ps1
  infrastructure/utils/scripts/shell/ubuntu_requirements.sh
Labels: Enhancement, Utils

#771 Added changes in Extensions.Csharp in changelog
  CHANGELOG.md
Labels: Documentation

#749 Lzk/public eks
  infrastructure/quick-deploy/aws/Makefile
  infrastructure/quick-deploy/aws/README.md
  infrastructure/quick-deploy/aws/eks/Makefile
  infrastructure/quick-deploy/aws/eks/locals.tf
  infrastructure/quick-deploy/aws/eks/main.tf
  infrastructure/quick-deploy/aws/eks/variables.tf
  infrastructure/quick-deploy/aws/envvars.sh
  infrastructure/quick-deploy/aws/vpc/Makefile
  infrastructure/quick-deploy/aws/vpc/locals.tf
  infrastructure/quick-deploy/aws/vpc/main.tf
  infrastructure/quick-deploy/aws/vpc/variables.tf
Labels: Enhancement

#787 Update to core 0.8.2
  CHANGELOG.md
  armonik-versions.txt
  infrastructure/quick-deploy/aws/armonik/parameters.tfvars
  infrastructure/quick-deploy/aws/ecr/parameters.tfvars
  infrastructure/quick-deploy/aws/monitoring/locals.tf
  infrastructure/quick-deploy/aws/monitoring/parameters.tfvars
  infrastructure/quick-deploy/localhost/armonik/parameters.tfvars
  infrastructure/quick-deploy/localhost/monitoring/locals.tf
  infrastructure/quick-deploy/localhost/monitoring/parameters.tfvars
Labels: Core
