Repository aneoconsulting/ArmoniK, pull requests merged in 2022-10, with the labels that each got.

#582 docs: fix links to tests scripts
  Documentation/articles/Tests/simple_tests.md
Labels: Documentation

#591 Fixed missing service disabling in powershell deployment script
  infrastructure/utils/scripts/armonik_dev_environment.ps1
  infrastructure/utils/scripts/shell/armonik_installation.sh
Labels: Bug

#655 Updated doc action
  .github/workflows/build_documentations.yml
Labels: Dependencies

#658 Fixed warning appearing in ExtCsharp due to this action.yml
  action.yml
Labels: Dependencies
