Repository aneoconsulting/ArmoniK, pull requests merged in 2023-06, with the labels that each got.

#1106 docs: rename and fix typos in benchmarking
  .docs/content/3.benchmarking/0.test-plan.md
  .docs/content/3.benchmarking/_dir.yml
  .docs/content/3.benchmarking/benchmarking-armonik-v2.10.4.md
  .docs/content/3.benchmarking/benchmarking-armonik-v2.10.5.md
  .docs/content/3.benchmarking/benchmarking-armonik-v2.12.3.md
  .vscode/extensions.json
Labels: Documentation

#1130 feat: upgrade iops for db node
  infrastructure/quick-deploy/aws/all/parameters.tfvars
  infrastructure/quick-deploy/aws/eks/parameters.tfvars
Labels: Enhancement, Performance

#1146 docs: add terminal into code blocks
  .docs/content/1.installation/1.linux/0.prerequisites.md
  .docs/content/1.installation/1.linux/1.installation.md
  .docs/content/1.installation/1.linux/2.verify-installation.md
  .docs/content/1.installation/1.linux/3.deploy-script.md
  .docs/content/1.installation/2.windows/0.installation-using-wsl2.md
  .docs/content/1.installation/2.windows/1.wsl2-with-systemd.md
  .docs/content/1.installation/2.windows/2.wsl2-with-genie.md
  .docs/content/1.installation/2.windows/3.useful-commands-for-wsl2.md
  .docs/content/1.installation/3.aws/aws-deployment-using-k3s.md
  .docs/content/1.installation/3.aws/aws-deployment-using-kubeadm.md
  .docs/content/2.guide/1.how-to/how-to-configure-authentication.md
  .docs/content/2.guide/1.how-to/how-to-configure-seq.md
Labels: Documentation

#1104 feat: add scripts to seed database
  .docs/content/2.guide/populate-database.md
  .gitignore
  .vscode/extensions.json
  infrastructure/utils/scripts/installation/prerequisites-installer.sh
  tools/export-mongo.sh
  tools/mongodb/.gitignore
  tools/mongodb/export-all.sh
  tools/mongodb/generate-partitions.sh
  tools/mongodb/generate-session-with-related-tasks.sh
  tools/mongodb/generate-sessions.sh
  tools/mongodb/generate-tasks.sh
  tools/mongodb/scripts/export-all.js
  tools/mongodb/scripts/generate-partitions.js
  tools/mongodb/scripts/generate-session-with-related-tasks.js
  tools/mongodb/scripts/generate-sessions.js
  tools/mongodb/scripts/generate-tasks.js
  tools/mongodb/scripts/package-lock.json
  tools/mongodb/scripts/package.json
  tools/mongodb/utils/clean-certificate.sh
  tools/mongodb/utils/execute-mongo-shell-script.sh
  tools/mongodb/utils/generate-certificate.sh
  tools/mongodb/utils/mongodb-ip.sh
  tools/mongodb/utils/mongodb-password.sh
  tools/mongodb/utils/mongodb-username.sh
Labels: GUI

#1151 docs: update readme
  README.md
Labels: Documentation
