Repository aneoconsulting/ArmoniK, pull requests merged in 2023-01, with the labels that each got.

#789 Don't deploy EFS by default
  infrastructure/quick-deploy/aws/storage/parameters.tfvars
Labels: Enhancement

#812 ECR images with prefix
  infrastructure/modules/aws/ecr/ecr.tf
  infrastructure/modules/aws/ecr/variables.tf
  infrastructure/quick-deploy/aws/Makefile
  infrastructure/quick-deploy/aws/backend/Makefile
  infrastructure/quick-deploy/aws/ecr/locals.tf
  infrastructure/quick-deploy/aws/ecr/main.tf
Labels: Enhancement

#814 Lzk/aws profile
  infrastructure/modules/aws/eks/eks-cluster.tf
  infrastructure/modules/aws/eks/locals.tf
  infrastructure/modules/aws/eks/update-kubeconfig.tf
  infrastructure/modules/aws/eks/variables.tf
  infrastructure/quick-deploy/aws/Makefile
  infrastructure/quick-deploy/aws/eks/main.tf
Labels: Enhancement

#837 fix(ci): Adapt pipeline to the new method to install docfx
  .github/workflows/build_documentations.yml
Labels: Bug, Documentation

#836 Parametrized configmaps
  infrastructure/modules/armonik/compute-plane-confimap.tf
  infrastructure/modules/armonik/control-plane-configmap.tf
  infrastructure/modules/armonik/core-configmap.tf
  infrastructure/modules/armonik/locals.tf
  infrastructure/modules/armonik/log-configmap.tf
  infrastructure/modules/armonik/polling-agent-configmap.tf
  infrastructure/modules/armonik/variables.tf
  infrastructure/modules/armonik/worker-configmap.tf
  infrastructure/quick-deploy/aws/all/armonik.tf
  infrastructure/quick-deploy/aws/all/parameters.tfvars
  infrastructure/quick-deploy/aws/all/variables.tf
  infrastructure/quick-deploy/aws/armonik/main.tf
  infrastructure/quick-deploy/aws/armonik/parameters.tfvars
  infrastructure/quick-deploy/aws/armonik/variables.tf
  infrastructure/quick-deploy/aws/eks/versions.tf
  infrastructure/quick-deploy/aws/monitoring/versions.tf
  infrastructure/quick-deploy/aws/storage/versions.tf
  infrastructure/quick-deploy/localhost/all/armonik.tf
  infrastructure/quick-deploy/localhost/all/parameters.tfvars
  infrastructure/quick-deploy/localhost/all/variables.tf
  infrastructure/quick-deploy/localhost/armonik/main.tf
  infrastructure/quick-deploy/localhost/armonik/parameters.tfvars
  infrastructure/quick-deploy/localhost/armonik/variables.tf
  infrastructure/quick-deploy/localhost/armonik/versions.tf
  infrastructure/quick-deploy/localhost/keda/versions.tf
  infrastructure/quick-deploy/localhost/metrics-server/versions.tf
  infrastructure/quick-deploy/localhost/monitoring/versions.tf
  infrastructure/quick-deploy/localhost/storage/versions.tf
Labels: Infrastructure

#841 Update Ext.Csharp to 0.8.2
  CHANGELOG.md
  armonik-versions.txt
  infrastructure/quick-deploy/aws/all/parameters.tfvars
  infrastructure/quick-deploy/aws/armonik/parameters.tfvars
  infrastructure/quick-deploy/aws/ecr/parameters.tfvars
  infrastructure/quick-deploy/localhost/all/parameters.tfvars
  infrastructure/quick-deploy/localhost/armonik/parameters.tfvars
Labels: Enhancement

#845 Reduce the number of tests in the pipeline
  .github/workflows/deploy.yml
  tools/install/aws-cli.sh
Labels: Enhancement

#847 Fix namespaces in all-in-one deployments
  infrastructure/quick-deploy/aws/all/eks.tf
  infrastructure/quick-deploy/localhost/all/common.tf
  infrastructure/quick-deploy/localhost/all/storage.tf
Labels: Infrastructure

#846 doc: Add jupyter notebook with ArmoniK architecture diagrams
  docs/Architecture.ipynb
Labels: Documentation

#838 Default images for all-in-one local deployment
  docs/image-versions.md
  infrastructure/modules/default-images/outputs.tf
  infrastructure/modules/default-images/variables.tf
  infrastructure/quick-deploy/aws/all/Makefile
  infrastructure/quick-deploy/aws/all/armonik.tf
  infrastructure/quick-deploy/aws/all/common.tf
  infrastructure/quick-deploy/aws/all/ecr.tf
  infrastructure/quick-deploy/aws/all/eks.tf
  infrastructure/quick-deploy/aws/all/keda.tf
  infrastructure/quick-deploy/aws/all/metrics-server.tf
  infrastructure/quick-deploy/aws/all/monitoring.tf
  infrastructure/quick-deploy/aws/all/parameters.tfvars
  infrastructure/quick-deploy/aws/all/storage.tf
  infrastructure/quick-deploy/aws/all/variables.tf
  infrastructure/quick-deploy/localhost/all/Makefile
  infrastructure/quick-deploy/localhost/all/armonik.tf
  infrastructure/quick-deploy/localhost/all/common.tf
  infrastructure/quick-deploy/localhost/all/images.tf
  infrastructure/quick-deploy/localhost/all/keda.tf
  infrastructure/quick-deploy/localhost/all/metrics-server.tf
  infrastructure/quick-deploy/localhost/all/monitoring.tf
  infrastructure/quick-deploy/localhost/all/parameters.tfvars
  infrastructure/quick-deploy/localhost/all/storage.tf
  infrastructure/quick-deploy/localhost/all/variables.tf
  versions.tfvars.json
Labels: Infrastructure

#826 816_update terraform scripts to allow payload Storage in S3
  infrastructure/modules/armonik/core-configmap.tf
  infrastructure/modules/armonik/locals.tf
  infrastructure/modules/armonik/outputs.tf
  infrastructure/modules/armonik/polling-agent-configmap.tf
  infrastructure/modules/armonik/variables.tf
  infrastructure/modules/onpremise-storage/minio/locals.tf
  infrastructure/modules/onpremise-storage/minio/minio.tf
  infrastructure/modules/onpremise-storage/minio/outputs.tf
  infrastructure/modules/onpremise-storage/minio/variables.tf
  infrastructure/quick-deploy/aws/armonik/main.tf
  infrastructure/quick-deploy/aws/armonik/parameters.tfvars
  infrastructure/quick-deploy/aws/armonik/variables.tf
  infrastructure/quick-deploy/aws/storage/locals.tf
  infrastructure/quick-deploy/aws/storage/main.tf
  infrastructure/quick-deploy/aws/storage/outputs.tf
  infrastructure/quick-deploy/aws/storage/parameters.tfvars
  infrastructure/quick-deploy/aws/storage/s3-iam_storage.tf
  infrastructure/quick-deploy/aws/storage/variables.tf
  infrastructure/quick-deploy/localhost/armonik/Makefile
  infrastructure/quick-deploy/localhost/armonik/main.tf
  infrastructure/quick-deploy/localhost/armonik/parameters.tfvars
  infrastructure/quick-deploy/localhost/armonik/variables.tf
  infrastructure/quick-deploy/localhost/storage/main.tf
  infrastructure/quick-deploy/localhost/storage/outputs.tf
  infrastructure/quick-deploy/localhost/storage/parameters.tfvars
  infrastructure/quick-deploy/localhost/storage/variables.tf
Labels: Infrastructure

#850 docs: diagrams architecture corrections
  docs/Architecture.ipynb
Labels: Documentation

#852 Fix all in one for S3 object storage
  infrastructure/quick-deploy/aws/all/armonik.tf
  infrastructure/quick-deploy/aws/all/parameters.tfvars
  infrastructure/quick-deploy/aws/all/storage.tf
  infrastructure/quick-deploy/aws/all/variables.tf
  infrastructure/quick-deploy/localhost/all/armonik.tf
  infrastructure/quick-deploy/localhost/all/common.tf
  infrastructure/quick-deploy/localhost/all/parameters.tfvars
  infrastructure/quick-deploy/localhost/all/storage.tf
  infrastructure/quick-deploy/localhost/all/variables.tf
  versions.tfvars.json
Labels: Infrastructure
