Repository aneoconsulting/ArmoniK, pull requests merged in 2023-02, with the labels that each got.

#871 add script to connect to mongo for aws/k8s
  tools/access-mongo-from-kubernetes-as-admin.sh
Labels: Infrastructure

#886 allow local images for ecr uploads
  infrastructure/modules/aws/ecr/ecr.tf
Labels: Infrastructure

#879 Add secret for prometheus
  infrastructure/modules/armonik/locals.tf
  infrastructure/modules/armonik/secrets.tf
  infrastructure/quick-deploy/aws/all/monitoring.tf
  infrastructure/quick-deploy/aws/armonik/parameters.tfvars
  infrastructure/quick-deploy/aws/monitoring/secrets.tf
  infrastructure/quick-deploy/localhost/all/monitoring.tf
  infrastructure/quick-deploy/localhost/monitoring/secrets.tf
Labels: Fixed

#887 Fix the check of empty string
  infrastructure/modules/aws/ecr/ecr.tf
Labels: Bug

#885 Yk/update docker images version
  infrastructure/modules/onpremise-storage/activemq/configmaps.tf
  versions.tfvars.json
Labels: Enhancement, Infrastructure

#904 Fixed terraform,docker,aws,kubectl installation
  .github/workflows/deploy.yml
  action.yml
Labels: CICD

#903 Upgrade version of AWS EKS from 1.22 to 1.24
  infrastructure/quick-deploy/aws/all/parameters.tfvars
  infrastructure/quick-deploy/aws/eks/parameters.tfvars
Labels: Enhancement, Infrastructure

#906 Update helm chart of keda for kubernetes 124
  infrastructure/modules/monitoring/keda/charts/keda/.helmignore
  infrastructure/modules/monitoring/keda/charts/keda/Chart.yaml
  infrastructure/modules/monitoring/keda/charts/keda/Notes.txt
  infrastructure/modules/monitoring/keda/charts/keda/README.md
  infrastructure/modules/monitoring/keda/charts/keda/templates/01-serviceaccount.yaml
  infrastructure/modules/monitoring/keda/charts/keda/templates/02-crd-clustertriggerauthentications.yaml
  infrastructure/modules/monitoring/keda/charts/keda/templates/03-crd-scaledjobs.keda.sh.yaml
  infrastructure/modules/monitoring/keda/charts/keda/templates/04-crd-scaledobjects.keda.sh.yaml
  infrastructure/modules/monitoring/keda/charts/keda/templates/05-crd-triggerauthentications.keda.sh.yaml
  infrastructure/modules/monitoring/keda/charts/keda/templates/10-keda-clusterrole.yaml
  infrastructure/modules/monitoring/keda/charts/keda/templates/11-keda-clusterrolebinding.yaml
  infrastructure/modules/monitoring/keda/charts/keda/templates/12-keda-deployment.yaml
  infrastructure/modules/monitoring/keda/charts/keda/templates/13-keda-poddisruptionbudget.yaml
  infrastructure/modules/monitoring/keda/charts/keda/templates/14-keda-podmonitor.yaml
  infrastructure/modules/monitoring/keda/charts/keda/templates/15-keda-prometheusrules.yaml
  infrastructure/modules/monitoring/keda/charts/keda/templates/20-metrics-clusterrole.yaml
  infrastructure/modules/monitoring/keda/charts/keda/templates/21-metrics-clusterrolebinding.yaml
  infrastructure/modules/monitoring/keda/charts/keda/templates/22-metrics-deployment.yaml
  infrastructure/modules/monitoring/keda/charts/keda/templates/23-metrics-service.yaml
  infrastructure/modules/monitoring/keda/charts/keda/templates/24-metrics-apiservice.yaml
  infrastructure/modules/monitoring/keda/charts/keda/templates/25-metrics-poddisruptionbudget.yaml
  infrastructure/modules/monitoring/keda/charts/keda/templates/26-metrics-podmonitor.yaml
  infrastructure/modules/monitoring/keda/charts/keda/templates/NOTES.txt
  infrastructure/modules/monitoring/keda/charts/keda/templates/_helpers.tpl
  infrastructure/modules/monitoring/keda/charts/keda/values.yaml
  infrastructure/modules/monitoring/keda/keda.tf
  infrastructure/quick-deploy/aws/ecr/parameters.tfvars
  infrastructure/quick-deploy/aws/keda/parameters.tfvars
  infrastructure/quick-deploy/localhost/keda/parameters.tfvars
  versions.tfvars.json
Labels: Enhancement, Infrastructure

#910 fix node exporter deployment in "all in one" local
  infrastructure/quick-deploy/localhost/all/variables.tf
Labels: Bug

#911 Variabilize Helm charts versions and repositories of ArmoniK
  infrastructure/modules/aws/eks/cluster-autoscaler.tf
  infrastructure/modules/aws/eks/instance_refresh.tf
  infrastructure/modules/aws/eks/variables.tf
  infrastructure/modules/monitoring/keda/keda.tf
  infrastructure/modules/monitoring/keda/variables.tf
  infrastructure/modules/monitoring/metrics-server/metrics-server.tf
  infrastructure/modules/monitoring/metrics-server/variables.tf
  infrastructure/modules/persistent-volumes/efs/efs-csi.tf
  infrastructure/modules/persistent-volumes/efs/variables.tf
  infrastructure/quick-deploy/aws/all/eks.tf
  infrastructure/quick-deploy/aws/all/keda.tf
  infrastructure/quick-deploy/aws/all/metrics-server.tf
  infrastructure/quick-deploy/aws/all/storage.tf
  infrastructure/quick-deploy/aws/all/variables.tf
  infrastructure/quick-deploy/aws/eks/main.tf
  infrastructure/quick-deploy/aws/eks/parameters.tfvars
  infrastructure/quick-deploy/aws/eks/variables.tf
  infrastructure/quick-deploy/aws/keda/locals.tf
  infrastructure/quick-deploy/aws/keda/main.tf
  infrastructure/quick-deploy/aws/keda/parameters.tfvars
  infrastructure/quick-deploy/aws/keda/variables.tf
  infrastructure/quick-deploy/aws/metrics-server/locals.tf
  infrastructure/quick-deploy/aws/metrics-server/main.tf
  infrastructure/quick-deploy/aws/metrics-server/parameters.tfvars
  infrastructure/quick-deploy/aws/metrics-server/variables.tf
  infrastructure/quick-deploy/aws/storage/main.tf
  infrastructure/quick-deploy/aws/storage/parameters.tfvars
  infrastructure/quick-deploy/aws/storage/variables.tf
  infrastructure/quick-deploy/localhost/all/keda.tf
  infrastructure/quick-deploy/localhost/all/metrics-server.tf
  infrastructure/quick-deploy/localhost/all/variables.tf
  infrastructure/quick-deploy/localhost/keda/main.tf
  infrastructure/quick-deploy/localhost/keda/parameters.tfvars
  infrastructure/quick-deploy/localhost/keda/variables.tf
  infrastructure/quick-deploy/localhost/metrics-server/main.tf
  infrastructure/quick-deploy/localhost/metrics-server/parameters.tfvars
  infrastructure/quick-deploy/localhost/metrics-server/variables.tf
Labels: Enhancement, Infrastructure

#914 update eks from 1.24 to 1.25
  infrastructure/quick-deploy/aws/all/parameters.tfvars
  infrastructure/quick-deploy/aws/eks/parameters.tfvars
Labels: Enhancement, Infrastructure

#913 Fix default_secret_name is empty in service account
  action.yml
  infrastructure/modules/monitoring/fluent-bit/fluent-bit.tf
  infrastructure/modules/monitoring/fluent-bit/service-account.tf
  infrastructure/quick-deploy/localhost/docs/k3s.md
Labels: Enhancement

#917 Fix fluent bit
  infrastructure/modules/monitoring/fluent-bit/fluent-bit.tf
  infrastructure/modules/monitoring/fluent-bit/service-account.tf
Labels: Bug
