Repository aneoconsulting/ArmoniK, pull requests merged in 2023-04, with the labels that each got.

#938 Al/upgrade eks module from 17.24.0 to 19.10.0
  infrastructure/modules/aws/ecr/ecr.tf
  infrastructure/modules/aws/ecr/versions.tf
  infrastructure/modules/aws/eks/cluster-autoscaler.tf
  infrastructure/modules/aws/eks/costum_eni.tf
  infrastructure/modules/aws/eks/eks-cluster.tf
  infrastructure/modules/aws/eks/iam.tf
  infrastructure/modules/aws/eks/instance_refresh.tf
  infrastructure/modules/aws/eks/locals.tf
  infrastructure/modules/aws/eks/outputs.tf
  infrastructure/modules/aws/eks/patch-coredns.tf
  infrastructure/modules/aws/eks/update-kubeconfig.tf
  infrastructure/modules/aws/eks/variables.tf
  infrastructure/modules/aws/eks/versions.tf
  infrastructure/modules/aws/s3/versions.tf
  infrastructure/quick-deploy/aws/all/kms.tf
  infrastructure/quick-deploy/aws/all/monitoring.tf
  infrastructure/quick-deploy/aws/all/outputs.tf
  infrastructure/quick-deploy/aws/all/parameters.tfvars
  infrastructure/quick-deploy/aws/all/providers.tf
  infrastructure/quick-deploy/aws/all/storage.tf
  infrastructure/quick-deploy/aws/all/versions.tf
  infrastructure/quick-deploy/aws/ecr/versions.tf
  infrastructure/quick-deploy/aws/eks/locals.tf
  infrastructure/quick-deploy/aws/eks/main.tf
  infrastructure/quick-deploy/aws/eks/outputs.tf
  infrastructure/quick-deploy/aws/eks/parameters.tfvars
  infrastructure/quick-deploy/aws/eks/providers.tf
  infrastructure/quick-deploy/aws/eks/versions.tf
  infrastructure/quick-deploy/aws/monitoring/iam.tf
  infrastructure/quick-deploy/aws/storage/locals.tf
  infrastructure/quick-deploy/aws/storage/s3-iam-object-storage.tf
  infrastructure/quick-deploy/aws/storage/s3-iam.tf
  infrastructure/quick-deploy/aws/storage/versions.tf
  infrastructure/quick-deploy/aws/vpc/versions.tf
Labels: Infrastructure

#967 docs: update pnpm version
  .docs/package.json
  .docs/pnpm-lock.yaml
Labels: Documentation

#978 fix creation date tag value : month/minute
  infrastructure/quick-deploy/aws/all/common.tf
  infrastructure/quick-deploy/aws/eks/locals.tf
Labels: Infrastructure

#958 avoid ingress_conf_file recreation at each terraform apply
  infrastructure/modules/armonik/locals.tf
  infrastructure/modules/armonik/variables.tf
  infrastructure/quick-deploy/aws/all/armonik.tf
  infrastructure/quick-deploy/localhost/all/armonik.tf
Labels: Infrastructure

#981 Add dependency to Keda
  infrastructure/modules/armonik/compute-plane-hpa.tf
  infrastructure/modules/armonik/control-plane-hpa.tf
  infrastructure/modules/armonik/variables.tf
  infrastructure/modules/monitoring/keda/outputs.tf
  infrastructure/modules/monitoring/metrics-server/outputs.tf
  infrastructure/modules/onpremise-storage/mongodb/outputs.tf
  infrastructure/quick-deploy/aws/all/armonik.tf
  infrastructure/quick-deploy/localhost/all/armonik.tf
Labels: Bug, Infrastructure

#969 957 add s3 as output to fluent bit
  infrastructure/modules/monitoring/fluent-bit/configs/input/input-kubernetes-daemonset.conf
  infrastructure/modules/monitoring/fluent-bit/configs/input/input-kubernetes-sidecar.conf
  infrastructure/modules/monitoring/fluent-bit/configs/output/output-cloudwatch.conf
  infrastructure/modules/monitoring/fluent-bit/configs/output/output-s3.conf
  infrastructure/modules/monitoring/fluent-bit/configs/service/fluent-bit.conf
  infrastructure/modules/monitoring/fluent-bit/envvars-configmap.tf
  infrastructure/modules/monitoring/fluent-bit/fluent-bit-configmap.tf
  infrastructure/modules/monitoring/fluent-bit/locals.tf
  infrastructure/modules/monitoring/fluent-bit/variables.tf
  infrastructure/quick-deploy/aws/Makefile
  infrastructure/quick-deploy/aws/all/monitoring.tf
  infrastructure/quick-deploy/aws/all/variables.tf
  infrastructure/quick-deploy/aws/monitoring/Makefile
  infrastructure/quick-deploy/aws/monitoring/iam.tf
  infrastructure/quick-deploy/aws/monitoring/locals.tf
  infrastructure/quick-deploy/aws/monitoring/main.tf
  infrastructure/quick-deploy/aws/monitoring/parameters.tfvars
  infrastructure/quick-deploy/aws/monitoring/variables.tf
Labels: Enhancement

#990 Enhance the use of the kubeconfig in AWS version
  CHANGELOG.md
  infrastructure/modules/armonik/external-data.tf
  infrastructure/modules/armonik/partitions-in-database.tf
  infrastructure/modules/aws/eks/cluster-autoscaler.tf
  infrastructure/modules/aws/eks/costum-eni.tf
  infrastructure/modules/aws/eks/eks-cluster.tf
  infrastructure/modules/aws/eks/instance-refresh.tf
  infrastructure/modules/aws/eks/locals.tf
  infrastructure/modules/aws/eks/outputs.tf
  infrastructure/modules/aws/eks/patch-coredns.tf
  infrastructure/modules/aws/eks/update-kubeconfig.tf
  infrastructure/modules/aws/eks/variables.tf
  infrastructure/modules/monitoring/exporters/metrics-exporter/locals.tf
  infrastructure/modules/monitoring/exporters/partition-metrics-exporter/locals.tf
  infrastructure/modules/monitoring/grafana/locals.tf
  infrastructure/modules/monitoring/prometheus/locals.tf
  infrastructure/modules/monitoring/seq/locals.tf
  infrastructure/modules/onpremise-storage/activemq/external-data.tf
  infrastructure/modules/onpremise-storage/mongodb/certificates.tf
  infrastructure/modules/onpremise-storage/mongodb/configmap.tf
  infrastructure/modules/onpremise-storage/redis/external-data.tf
  infrastructure/quick-deploy/aws/Makefile
  infrastructure/quick-deploy/aws/all/Makefile
  infrastructure/quick-deploy/aws/all/eks.tf
  infrastructure/quick-deploy/aws/all/outputs.tf
  infrastructure/quick-deploy/aws/all/parameters.tfvars
  infrastructure/quick-deploy/aws/all/variables.tf
  infrastructure/quick-deploy/aws/armonik/Makefile
  infrastructure/quick-deploy/aws/armonik/providers.tf
  infrastructure/quick-deploy/aws/backend/Makefile
  infrastructure/quick-deploy/aws/eks/Makefile
  infrastructure/quick-deploy/aws/eks/main.tf
  infrastructure/quick-deploy/aws/eks/outputs.tf
  infrastructure/quick-deploy/aws/eks/parameters.tfvars
  infrastructure/quick-deploy/aws/eks/variables.tf
  infrastructure/quick-deploy/aws/keda/Makefile
  infrastructure/quick-deploy/aws/keda/providers.tf
  infrastructure/quick-deploy/aws/metrics-server/Makefile
  infrastructure/quick-deploy/aws/metrics-server/providers.tf
  infrastructure/quick-deploy/aws/monitoring/Makefile
  infrastructure/quick-deploy/aws/monitoring/providers.tf
  infrastructure/quick-deploy/aws/storage/Makefile
  infrastructure/quick-deploy/aws/storage/providers.tf
  infrastructure/utils/scripts/k8s_config.sh
Labels: Bug, Enhancement

#985 979 manage the parser in the input config of the fluent bit
  infrastructure/modules/monitoring/fluent-bit/configs/input/input-kubernetes-daemonset.conf
  infrastructure/modules/monitoring/fluent-bit/configs/input/input-kubernetes-sidecar.conf
  infrastructure/modules/monitoring/fluent-bit/envvars-configmap.tf
  infrastructure/modules/monitoring/fluent-bit/locals.tf
  infrastructure/modules/monitoring/fluent-bit/variables.tf
  infrastructure/quick-deploy/aws/all/monitoring.tf
  infrastructure/quick-deploy/aws/all/variables.tf
  infrastructure/quick-deploy/aws/monitoring/locals.tf
  infrastructure/quick-deploy/aws/monitoring/main.tf
  infrastructure/quick-deploy/aws/monitoring/parameters.tfvars
  infrastructure/quick-deploy/aws/monitoring/variables.tf
  infrastructure/quick-deploy/localhost/all/monitoring.tf
  infrastructure/quick-deploy/localhost/all/variables.tf
  infrastructure/quick-deploy/localhost/monitoring/locals.tf
  infrastructure/quick-deploy/localhost/monitoring/main.tf
  infrastructure/quick-deploy/localhost/monitoring/parameters.tfvars
  infrastructure/quick-deploy/localhost/monitoring/variables.tf
Labels: Enhancement

#994 fix: Retries for mongodb replica set
  infrastructure/modules/onpremise-storage/mongodb/configmap.tf
Labels: Bug, Infrastructure

#971 Add retention limit in seq
  CHANGELOG.md
  infrastructure/modules/monitoring/seq/retention-job.tf
  infrastructure/modules/monitoring/seq/variables.tf
  infrastructure/quick-deploy/aws/all/ecr.tf
  infrastructure/quick-deploy/aws/all/monitoring.tf
  infrastructure/quick-deploy/aws/all/parameters.tfvars
  infrastructure/quick-deploy/aws/all/variables.tf
  infrastructure/quick-deploy/aws/ecr/parameters.tfvars
  infrastructure/quick-deploy/aws/monitoring/locals.tf
  infrastructure/quick-deploy/aws/monitoring/main.tf
  infrastructure/quick-deploy/aws/monitoring/parameters.tfvars
  infrastructure/quick-deploy/aws/monitoring/variables.tf
  infrastructure/quick-deploy/localhost/Makefile
  infrastructure/quick-deploy/localhost/all/monitoring.tf
  infrastructure/quick-deploy/localhost/all/variables.tf
  infrastructure/quick-deploy/localhost/monitoring/locals.tf
  infrastructure/quick-deploy/localhost/monitoring/main.tf
  infrastructure/quick-deploy/localhost/monitoring/parameters.tfvars
  infrastructure/quick-deploy/localhost/monitoring/variables.tf
  versions.tfvars.json
Labels: Infrastructure

#1002 chore: Update kubeconfig target in makefile for AWS version
  infrastructure/quick-deploy/aws/Makefile
  infrastructure/quick-deploy/aws/all/Makefile
Labels: Enhancement

#1007 chore: Add command to update KUBECONFIG in output of Terraform
  infrastructure/quick-deploy/aws/Makefile
  infrastructure/quick-deploy/aws/all/Makefile
  infrastructure/quick-deploy/aws/all/outputs.tf
  infrastructure/quick-deploy/aws/eks/outputs.tf
Labels: Enhancement

#1006 ci: increase timeout in pipelines
  .github/workflows/deploy.yml
Labels: CICD

#1008 docs: add test plan
  .docs/test_plan.md
Labels: Documentation

#1010 feat: Add configuration in KEDA
  CHANGELOG.md
  infrastructure/modules/monitoring/keda/keda.tf
  infrastructure/modules/monitoring/keda/variables.tf
  infrastructure/quick-deploy/aws/all/keda.tf
  infrastructure/quick-deploy/aws/all/variables.tf
  infrastructure/quick-deploy/aws/keda/locals.tf
  infrastructure/quick-deploy/aws/keda/main.tf
  infrastructure/quick-deploy/aws/keda/parameters.tfvars
  infrastructure/quick-deploy/aws/keda/variables.tf
  infrastructure/quick-deploy/localhost/all/keda.tf
  infrastructure/quick-deploy/localhost/all/variables.tf
  infrastructure/quick-deploy/localhost/keda/main.tf
  infrastructure/quick-deploy/localhost/keda/parameters.tfvars
  infrastructure/quick-deploy/localhost/keda/variables.tf
Labels: Enhancement

#1013 docs: set kubctl context
  infrastructure/quick-deploy/aws/Makefile
  infrastructure/quick-deploy/aws/all/Makefile
  infrastructure/quick-deploy/aws/all/outputs.tf
  infrastructure/quick-deploy/aws/eks/outputs.tf
Labels: Documentation

#1016 fix: add armonik metrics services and update k3s version for wsl deployment
  infrastructure/utils/scripts/shell/armonik_installation.sh
  infrastructure/utils/scripts/shell/armonik_requirements.sh
Labels: Bug

#1024 fix: Lowered tls requirement and change cname of pregenerated certificate
  infrastructure/modules/armonik/ingress-cert.tf
  infrastructure/modules/armonik/ingress-configmap.tf
Labels: Security

#1028 docs: fix links in readme
  README.md
Labels: Documentation

#1029 fix: Update EKS module and parameters
  armonik-versions.txt
  infrastructure/modules/aws/eks/cluster-autoscaler.tf
  infrastructure/modules/aws/eks/eks-cluster.tf
  infrastructure/modules/aws/eks/locals.tf
  infrastructure/modules/aws/eks/variables.tf
  infrastructure/quick-deploy/aws/all/eks.tf
  infrastructure/quick-deploy/aws/all/parameters.tfvars
  infrastructure/quick-deploy/aws/all/variables.tf
  infrastructure/quick-deploy/aws/eks/main.tf
  infrastructure/quick-deploy/aws/eks/parameters.tfvars
  infrastructure/quick-deploy/aws/eks/variables.tf
  versions.tfvars.json
Labels: Infrastructure

#1032 feat: Queue adapter to choice dynamically
  CHANGELOG.md
  armonik-versions.txt
  infrastructure/modules/armonik/core-configmap.tf
  infrastructure/modules/aws/mq/outputs.tf
  infrastructure/modules/aws/mq/variables.tf
  infrastructure/modules/onpremise-storage/activemq/locals.tf
  infrastructure/modules/onpremise-storage/activemq/outputs.tf
  infrastructure/modules/onpremise-storage/activemq/secrets.tf
  infrastructure/quick-deploy/aws/all/common.tf
  infrastructure/quick-deploy/aws/all/storage.tf
  infrastructure/quick-deploy/aws/armonik/parameters.tfvars
  infrastructure/quick-deploy/aws/ecr/parameters.tfvars
  infrastructure/quick-deploy/aws/monitoring/parameters.tfvars
  infrastructure/quick-deploy/aws/storage/locals.tf
  infrastructure/quick-deploy/aws/storage/secrets.tf
  infrastructure/quick-deploy/localhost/all/storage.tf
  infrastructure/quick-deploy/localhost/armonik/parameters.tfvars
  infrastructure/quick-deploy/localhost/monitoring/parameters.tfvars
  infrastructure/quick-deploy/localhost/storage/outputs.tf
  infrastructure/quick-deploy/localhost/storage/secrets.tf
  versions.tfvars.json
Labels: Enhancement, Infrastructure

#1042 fix: ACLs in S3 module
  infrastructure/modules/aws/s3/s3.tf
  infrastructure/modules/aws/s3/variables.tf
  infrastructure/quick-deploy/aws/all/storage.tf
  infrastructure/quick-deploy/aws/all/variables.tf
  infrastructure/quick-deploy/aws/storage/main.tf
  infrastructure/quick-deploy/aws/storage/parameters.tfvars
  infrastructure/quick-deploy/aws/storage/variables.tf
Labels: Bug, Infrastructure

#1041 feat: add minio as zip storage for localhost deployment
  infrastructure/modules/armonik/ingress-configmap.tf
  infrastructure/modules/armonik/locals.tf
  infrastructure/modules/onpremise-storage/minio/locals.tf
  infrastructure/modules/onpremise-storage/minio/minio.tf
  infrastructure/modules/onpremise-storage/minio/outputs.tf
  infrastructure/quick-deploy/localhost/all/common.tf
  infrastructure/quick-deploy/localhost/all/parameters.tfvars
  infrastructure/quick-deploy/localhost/all/providers.tf
  infrastructure/quick-deploy/localhost/all/storage.tf
  infrastructure/quick-deploy/localhost/all/variables.tf
  infrastructure/quick-deploy/localhost/armonik/providers.tf
  infrastructure/quick-deploy/localhost/keda/providers.tf
  infrastructure/quick-deploy/localhost/metrics-server/parameters.tfvars
  infrastructure/quick-deploy/localhost/metrics-server/providers.tf
  infrastructure/quick-deploy/localhost/monitoring/providers.tf
  infrastructure/quick-deploy/localhost/storage/locals.tf
  infrastructure/quick-deploy/localhost/storage/main.tf
  infrastructure/quick-deploy/localhost/storage/outputs.tf
  infrastructure/quick-deploy/localhost/storage/parameters.tfvars
  infrastructure/quick-deploy/localhost/storage/providers.tf
  infrastructure/quick-deploy/localhost/storage/secrets.tf
  infrastructure/quick-deploy/localhost/storage/variables.tf
  infrastructure/utils/scripts/k8s_config.sh
Labels: Infrastructure
