Repository aneoconsulting/ArmoniK, pull requests merged in 2023-05, with the labels that each got.

#1048 chore: update docs deps
  .docs/package.json
  .docs/pnpm-lock.yaml
Labels: Documentation

#1046 ci: add extra json for cicd
  extra.tfvars.json
  infrastructure/quick-deploy/aws/all/Makefile
  infrastructure/quick-deploy/localhost/all/Makefile
Labels: CICD

#1053 feat: 1043 use different node groups in kubernetes cluster
  infrastructure/modules/armonik/ingress.tf
  infrastructure/modules/armonik/locals.tf
  infrastructure/modules/aws/eks/autoscaling-group-tag.tf
  infrastructure/modules/aws/eks/eks-cluster.tf
  infrastructure/modules/aws/eks/locals.tf
  infrastructure/modules/aws/eks/outputs.tf
  infrastructure/modules/aws/eks/variables.tf
  infrastructure/modules/monitoring/exporters/node-exporter/node-exporter.tf
  infrastructure/quick-deploy/aws/all/eks.tf
  infrastructure/quick-deploy/aws/all/monitoring.tf
  infrastructure/quick-deploy/aws/all/parameters.tfvars
  infrastructure/quick-deploy/aws/all/storage.tf
  infrastructure/quick-deploy/aws/all/variables.tf
  infrastructure/quick-deploy/aws/armonik/parameters.tfvars
  infrastructure/quick-deploy/aws/eks/outputs.tf
  infrastructure/quick-deploy/aws/eks/parameters.tfvars
  infrastructure/quick-deploy/aws/keda/parameters.tfvars
  infrastructure/quick-deploy/aws/metrics-server/parameters.tfvars
  infrastructure/quick-deploy/aws/monitoring/iam.tf
  infrastructure/quick-deploy/aws/monitoring/parameters.tfvars
  infrastructure/quick-deploy/aws/storage/parameters.tfvars
  infrastructure/quick-deploy/aws/storage/s3-iam-object-storage.tf
  infrastructure/quick-deploy/aws/storage/s3-iam.tf
  infrastructure/quick-deploy/localhost/all/variables.tf
Labels: Enhancement, Infrastructure

#1049 docs: update guides
  .docs/content/0.armonik/0.index.md
  .docs/content/2.guide/0.index.md
  .docs/content/2.guide/1.how-to/_dir.yml
  .docs/content/2.guide/1.how-to/how-to-configure-authentication.md
  .docs/content/2.guide/1.how-to/how-to-configure-partitions.md
  .docs/content/2.guide/1.how-to/how-to-configure-seq.md
  .docs/content/2.guide/clientlargetasks-state-diagram.md
  .docs/content/2.guide/debug.md
  .docs/content/2.guide/default-images.md
  .docs/content/2.guide/happy-flow-diagram-sequence.md
  .docs/content/2.guide/nice-charts-howto.md
  .docs/content/2.guide/polling-agent.md
Labels: Documentation

#1051 docs: fix aws deployment
  .docs/content/1.installation/3.aws/aws-deployment-using-k3s.md
  .docs/content/1.installation/3.aws/aws-deployment-using-kubeadm.md
Labels: Documentation

#1065 style: add linter to docs
  .docs/.eslintignore
  .docs/.eslintrc
  .docs/.gitignore
  .docs/.markdownlint.yml
  .docs/.markdownlintignore
  .docs/README.md
  .docs/app.config.ts
  .docs/content/0.armonik/0.index.md
  .docs/content/0.armonik/components/3.armonik/4.admin-gui.md
  .docs/content/1.installation/1.linux/0.prerequisites.md
  .docs/content/1.installation/1.linux/1.installation.md
  .docs/content/1.installation/1.linux/2.verify-installation.md
  .docs/content/1.installation/2.windows/3.useful-commands-for-wsl2.md
  .docs/content/1.installation/3.aws/aws-deployment-using-k3s.md
  .docs/content/1.installation/3.aws/aws-deployment-using-kubeadm.md
  .docs/content/2.guide/1.how-to/how-to-configure-authentication.md
  .docs/content/2.guide/1.how-to/how-to-configure-partitions.md
  .docs/content/2.guide/1.how-to/how-to-configure-seq.md
  .docs/content/2.guide/clientlargetasks-state-diagram.md
  .docs/content/2.guide/default-images.md
  .docs/content/2.guide/happy-flow-diagram-sequence.md
  .docs/content/2.guide/polling-agent.md
  .docs/nuxt.config.ts
  .docs/package.json
  .docs/pnpm-lock.yaml
  .docs/test_plan.md
  .github/workflows/validate-docs-generation.yml
Labels: Documentation

#1069 refactor: add helm charts repositories and versions in json file
  infrastructure/quick-deploy/aws/all/eks.tf
  infrastructure/quick-deploy/aws/all/keda.tf
  infrastructure/quick-deploy/aws/all/metrics-server.tf
  infrastructure/quick-deploy/aws/all/storage.tf
  infrastructure/quick-deploy/aws/all/variables.tf
  infrastructure/quick-deploy/localhost/all/keda.tf
  infrastructure/quick-deploy/localhost/all/metrics-server.tf
  infrastructure/quick-deploy/localhost/all/variables.tf
  versions.tfvars.json
Labels: Enhancement

#1078 Yk/pre 2.10.4
  CHANGELOG.md
  infrastructure/modules/aws/s3/s3.tf
  infrastructure/quick-deploy/aws/ecr/parameters.tfvars
Labels: Fixed

#1073 refactor: Rename modules sources
  CHANGELOG.md
  armonik-versions.txt
  infrastructure/quick-deploy/aws/all/ecr.tf
  infrastructure/quick-deploy/aws/all/eks.tf
  infrastructure/quick-deploy/aws/all/keda.tf
  infrastructure/quick-deploy/aws/all/kms.tf
  infrastructure/quick-deploy/aws/all/metrics-server.tf
  infrastructure/quick-deploy/aws/all/monitoring.tf
  infrastructure/quick-deploy/aws/all/storage.tf
  infrastructure/quick-deploy/aws/all/vpc.tf
  infrastructure/quick-deploy/aws/ecr/main.tf
  infrastructure/quick-deploy/aws/eks/main.tf
  infrastructure/quick-deploy/aws/keda/main.tf
  infrastructure/quick-deploy/aws/metrics-server/main.tf
  infrastructure/quick-deploy/aws/monitoring/main.tf
  infrastructure/quick-deploy/aws/storage/main.tf
  infrastructure/quick-deploy/aws/vpc/main.tf
  infrastructure/quick-deploy/localhost/all/images.tf
  infrastructure/quick-deploy/localhost/all/keda.tf
  infrastructure/quick-deploy/localhost/all/metrics-server.tf
  infrastructure/quick-deploy/localhost/all/monitoring.tf
  infrastructure/quick-deploy/localhost/all/storage.tf
  infrastructure/quick-deploy/localhost/keda/main.tf
  infrastructure/quick-deploy/localhost/metrics-server/main.tf
  infrastructure/quick-deploy/localhost/monitoring/main.tf
  infrastructure/quick-deploy/localhost/storage/main.tf
  versions.tfvars.json
Labels: Infrastructure

#1081 fix: update ArmoniK.Core version with some backported bug corrections (metrics exporter)
  .github/workflows/deploy.yml
  CHANGELOG.md
  armonik-versions.txt
  infrastructure/quick-deploy/aws/armonik/parameters.tfvars
  infrastructure/quick-deploy/aws/ecr/parameters.tfvars
  infrastructure/quick-deploy/aws/monitoring/locals.tf
  infrastructure/quick-deploy/aws/monitoring/parameters.tfvars
  infrastructure/quick-deploy/localhost/armonik/parameters.tfvars
  infrastructure/quick-deploy/localhost/monitoring/locals.tf
  infrastructure/quick-deploy/localhost/monitoring/parameters.tfvars
Labels: Bug, Support

#1086 docs: fix lint markdown
  .docs/benchmarking/stats_v2.12.3.md
  .docs/test_plan.md
Labels: Documentation

#1097 chore: Update Samples version
  armonik-versions.txt
Labels: Enhancement

#1098 docs: benchmarking stats of the version 2.10.4 of ArmoniK
  .docs/content/3.benchmarking/stats_v2.10.4.md
  benchmarking/benchmarking_stats.csv
Labels: Documentation, Tests
